import {initial,legalMoves,apply,play,inCheck,outcome,color} from './rules.js';
const $=id=>document.getElementById(id),symbols={K:'♔',Q:'♕',R:'♖',B:'♗',N:'♘',P:'♙',k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'};
let mode='hot',side='w',position=initial(),selected=-1,last=null,room='',role='watch',socket=null,revision=0,busy=false,notice='';
const codePattern=/^[A-Z0-9]{4,12}$/;
function key(room){return 'chin-tucked-identity:'+room}
function identity(room){let v=localStorage.getItem(key(room));if(!v||! /^[a-f0-9]{32}$/.test(v)){v=Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');localStorage.setItem(key(room),v)}return v}
function canMove(){return mode==='hot'||mode==='computer'&&position.turn===side&&!busy||mode==='online'&&role===(position.turn==='w'?'white':'black')&&socket?.readyState===WebSocket.OPEN}
function caption(){const result=outcome(position),who=position.turn==='w'?'WHITE':'BLACK';$('turn-heading').textContent=result==='checkmate'?`${who} IS CHECKMATED`:result==='stalemate'?'STALEMATE':`${who} TO MOVE`;$('status').textContent=notice||({check:`${who} is in check. Protect your king.`,checkmate:`${who==='WHITE'?'Black':'White'} wins.`,stalemate:'No legal move remains. The game is a draw.',playing:mode==='online'&&role==='watch'?'Watching the room.':mode==='online'&&!canMove()?'Waiting for the other player.':mode==='computer'&&busy?'Computer is thinking.':'Choose a piece to see where it can go.'})[result];$('mode-label').textContent={hot:'HOT-SEAT',computer:'VS COMPUTER',online:'ONLINE'}[mode];$('role-label').textContent=mode==='hot'?'BOTH PLAYERS':mode==='computer'?(side==='w'?'WHITE':'BLACK'):role.toUpperCase();$('room-label').textContent=mode==='online'?room:'—';$('bottom-label').textContent=mode==='computer'&&side==='b'?'BLACK':'WHITE';$('top-label').textContent=mode==='computer'&&side==='b'?'WHITE':'BLACK'}
function render(){const board=$('board');board.replaceChildren();const opts=selected>=0&&canMove()?legalMoves(position).filter(m=>m.from===selected):[];const flipped=mode==='computer'&&side==='b';for(let view=0;view<64;view++){const i=flipped?63-view:view,p=position.board[i],x=i%8,y=i>>3,b=document.createElement('button');b.type='button';b.className='square '+((x+y)%2?'dark':'light');b.setAttribute('role','gridcell');b.setAttribute('aria-label',`${'abcdefgh'[x]}${8-y}: ${p==='.'?'empty':(color(p)==='w'?'white ':'black ')+({p:'pawn',n:'knight',b:'bishop',r:'rook',q:'queen',k:'king'})[p.toLowerCase()]}`);if(selected===i)b.classList.add('selected');if(last&&(last.from===i||last.to===i))b.classList.add('last');if(p.toLowerCase()==='k'&&color(p)===position.turn&&inCheck(position,position.turn))b.classList.add('in-check');if(opts.some(m=>m.to===i)){b.classList.add('legal');if(p!=='.')b.classList.add('capture')}if(p!=='.'){const span=document.createElement('span');span.className='piece '+(color(p)==='w'?'white':'black');span.textContent=symbols[p];b.append(span)}if(x===(flipped?7:0)){const label=document.createElement('span');label.className='coord';label.textContent=8-y;b.append(label)}b.addEventListener('click',()=>click(i));board.append(b)}caption()}
function commit(move){notice='';last=move;selected=-1;if(mode==='online'){socket.send(JSON.stringify({type:'move',payload:move}));return}position=play(position,move);render();if(mode==='computer'&&position.turn!==side&&['playing','check'].includes(outcome(position)))computerMove()}
function click(i){if(!canMove()||!['playing','check'].includes(outcome(position)))return;const options=selected>=0?legalMoves(position).filter(m=>m.from===selected&&m.to===i):[];if(options.length){if(options.some(m=>m.promotion)){const dialog=$('promotion'),choices=$('promotion-choices');choices.replaceChildren();for(const m of options){const b=document.createElement('button');b.type='button';b.textContent=symbols[position.turn==='w'?m.promotion.toUpperCase():m.promotion];b.setAttribute('aria-label',({q:'Queen',r:'Rook',b:'Bishop',n:'Knight'})[m.promotion]);b.onclick=()=>{dialog.close();commit(m)};choices.append(b)}dialog.showModal()}else commit(options[0]);return}selected=position.board[i]!=='.'&&color(position.board[i])===position.turn?i:-1;render()}
const values={p:100,n:320,b:330,r:500,q:900,k:20000};
function score(s){let v=0;for(const p of s.board)if(p!=='.')v+=(color(p)==='w'?1:-1)*values[p.toLowerCase()];return v*(side==='w'?-1:1)}
function search(s,depth,alpha,beta,deadline){if(performance.now()>deadline)return {score:score(s),expired:true};const moves=legalMoves(s);if(!moves.length)return {score:inCheck(s,s.turn)?(s.turn===side?100000:-100000):0};if(!depth)return {score:score(s)};const maximize=s.turn!==side;let best=maximize?-Infinity:Infinity;for(const m of moves){const r=search(apply(s,m),depth-1,alpha,beta,deadline);if(r.expired)return r;best=maximize?Math.max(best,r.score):Math.min(best,r.score);if(maximize)alpha=Math.max(alpha,best);else beta=Math.min(beta,best);if(beta<=alpha)break}return {score:best}}
function computerMove(){busy=true;render();const deadline=performance.now()+1900,moves=legalMoves(position);if(!moves.length){busy=false;render();return}let chosen=moves[0],best=-Infinity;for(const m of moves){if(performance.now()>deadline)break;const r=search(apply(position,m),1,-Infinity,Infinity,deadline);if(r.expired)break;if(r.score>best){best=r.score;chosen=m}}position=play(position,chosen);last=chosen;busy=false;render()}
function disconnect(){if(socket){socket.onclose=null;socket.close();socket=null}}
function connect(){disconnect();const scheme=location.protocol==='https:'?'wss':'ws',token=identity(room);socket=new WebSocket(`${scheme}://${location.host}/ws/${room}?token=${token}`);notice='Connecting to room…';render();socket.onmessage=event=>{let data;try{data=JSON.parse(event.data)}catch{return}if(data.type==='welcome'){role=data.payload.role;position=data.payload.position;revision=data.payload.revision;notice='';last=null;selected=-1}else if(data.type==='state'){if(data.payload.revision>revision){revision=data.payload.revision;position=data.payload.position;last=null;selected=-1;notice=''}}else if(data.type==='error')notice=data.payload.message;else if(data.type==='presence'&&role==='white'&&!data.payload.black)notice='Waiting for Black to join.';else if(data.type==='presence')notice='';render()};socket.onclose=()=>{notice='Disconnected. Rejoin the room to continue.';render()};socket.onerror=()=>{notice='Could not connect to the room.';render()}}
function switchMode(next){disconnect();mode=next;position=initial();selected=-1;last=null;busy=false;notice='';role='watch';document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('intro').hidden=mode!=='hot';$('computer-options').hidden=mode!=='computer';$('online-options').hidden=mode!=='online';render();if(mode==='computer'&&side==='b')computerMove()}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>switchMode(b.dataset.mode));$('side').onchange=e=>{side=e.target.value;switchMode('computer')};$('join').onclick=()=>{const code=$('room').value.trim().toUpperCase();if(!codePattern.test(code)){notice='Room codes need 4–12 letters or numbers.';render();return}room=code;$('room').value=code;history.replaceState(null,'',`/?room=${code}`);connect()};$('room').onkeydown=e=>{if(e.key==='Enter')$('join').click()};$('new-game').onclick=()=>{if(mode==='online'){if(role==='watch'){notice='Only players can start a new game.';render()}else if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type:'newGame',payload:{}}));return}position=initial();last=null;selected=-1;notice='';render();if(mode==='computer'&&side==='b')computerMove()};const fromUrl=new URLSearchParams(location.search).get('room');if(fromUrl&&codePattern.test(fromUrl.toUpperCase())){switchMode('online');room=fromUrl.toUpperCase();$('room').value=room;connect()}else render();
